name: Jacoco with Java Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  jacoco-java-gradle:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run Tests
      run: ./gradlew test

    - name: Run Test Coverage
      run: ./gradlew jacocoTestReport

    - name: Display local test coverage (only API 30)
      id: jacoco
      uses: madrapps/jacoco-report@v1.7.0
      with:
        title: Combined test coverage report
        min-coverage-overall: 40
        min-coverage-changed-files: 60
        paths: |
          ${{ github.workspace }}/**/build/reports/jacoco/**/*Report.xml
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload local coverage reports (XML + HTML)
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        if-no-files-found: error
        compression-level: 1
        overwrite: false
        path: '**/build/reports/jacoco/*' 

    - name: Set up SonarQube environment variables
      run: echo "SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}" >> $GITHUB_ENV

    - name: Run SonarQube analysis
      #run: ./gradlew sonar -Dsonar.host.url=https://sonarcloud.io 
      run: ./gradlew test jacocoTestReport sonarqube -Dsonar.host.url=https://sonarcloud.io
